### PR TITLE
it's honkai time

### LINKED ISSUE #4: Support Honkai Impact daily sign-in
Since honkai has its own daily sign-in rewards it'd be nice to support it in genshin.py.

The logic is the exact same, only the base url and act id differ.
The biggest problem is figuring out how to properly implement it without much repetition. 

Currently, users can use:
```py
class HonkaiClient(GenshinClient):
    ACT_ID = "e202110291205111"
    REWARD_URL = "https://api-os-takumi.mihoyo.com/event/mani/"
```
```py
client = HonkaiClient(...)
client.claim_daily_reward()
```

### PR DESCRIPTION
**Pull request by Sharp-Eyes**
Very much WIP branch focused on adding the new Honkai Impact Hoyolab API endpoints to genshin.py.  
Currently on the agenda:
- [ ] Extract generic `GenshinClient` functionality that applies to the entirety of Hoyolab into a new base Client,
- [ ] Add a HonkaiClient that derives from said new generic Client,
- [x] Add new Pydantic Models to parse the data returned by the Honkai Impact side into a more useable format,
- [ ] Add sufficient tests for all the changes (more like learn pytest altogether :/),
- [ ] Somehow convince Sadru that the code is good enough for a merge.

For now, while the extracting is still WIP, raw Honkai player data requests can be done as follows:
```py
client = GenshinClient()
client.set_cookies(ltuid="<my_ltuid>", ltoken="<my_ltoken>")

await client.request_game_record(
    "honkai3rd/api/<endpoint>",
    params={"server": "<my_server>", "role_id": "<my_honkai_UID>"}
)
```
> _Note: this code snippet is not complete, and will not run as-is (except in an iPython kernel/Jupyter notebook, etc.)_

...with any of the following endpoints (listed as endpoint name ~ Hoyolab website equivalent, respectively):
```
index             ~ Summary
characters        ~ My valkyries
godWar            ~ Elysian Realm
newAbyssReport    ~ Abyss Report
battleFieldReport ~ Arena Report
```
Please see the [extra/honkai_example.py](https://github.com/Chromosomologist/genshin.py/blob/honkai/extra/honkai_example.py) for a quick example of how the current (limited, WIP) implementation can be used to parse the returned data. Of course, keep in mind that this will be streamlined to work exactly the same as the current `GenshinClient` implementation.

Closes #4

### CODE REVIEW

**Comment by ashleney** [comment]
9bb24be15181204285366b34de77181fb335901a will have to be reverted, instead we will attempt to refactor in a better way

**Comment by Sharp-Eyes** [comment]
Something weird happened there trying to solve a merge conflict, doesn't seem to have broken anything, luckily. If the models look good to you, they should be just about finished now. One small thing left to implement regarding ER, and we should be good.

**Comment by Sharp-Eyes** [comment]
From this point onwards, any current Honkai HoYoLAB stuff can be done using a `genshin.OverseasHonkaiClient` for EU/NA/SEA server players. The entire CN side still has to be implemented, though. Here's a quick example:
```py
import asyncio
import genshin
cookies = {"ltuid": "17334943", "ltoken": "uEecA6eaelVrOoPwiVmLf880jeQlXB7srhtniGi1"}

async def main():
    async with genshin.OverseasHonkaiClient(cookies) as client:
        return await client.get_full_user(200365120)

full_stats = asyncio.run(main())
print(f"Most used char in ER: {full_stats.elysian_realm.battlesuit_info[0].name}")
print(f"Latest MA rank: {full_stats.memorial_arena[0].rank}")
print(f"Latest abyss rank: {full_stats.abyss[0].end_rank}")
```
I can probably still add some convenience methods to make it easier to navigate lists returned by the API, but at least all the data should be complete now, and the client should be operational.

**Comment by ashleney** [comment]
I think we should close this in the favor of the `rewrite` branch. You are free to make pull requests towards that branch if you want to improve the current partial honkai implementation.

**Pull request closed without merging**
