### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by LuckyTain**

### CODE REVIEW

**Comment by BobbyWibowo** [comment]
It was intentional, lmao

Here you go https://en.wikipedia.org/wiki/Engrish

**Comment by GauravM512** [comment]
Intentional not a typo error 🤗

**Comment by ashleney** [comment]
I think it would be best if I added an abbreviation tag for it so people do not get confused.

**Comment by LuckyTain** [comment]
Sorry for my misunderstanding 😂
Because in this sentence
「Chinese and **Engrish** names returned by the API are renamed to simpler **English** fields.」
There is a word `English`  at the end of the sentence

**Comment by ashleney** [comment]
I have no idea how else to word it.

**Pull request closed without merging**
